apiVersion: v1
kind: Service
metadata: 
  name: svc-wordpress
  namespace: labwordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
    - port: 80
      protocol: TCP